// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'daily_values.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

DailyValues _$DailyValuesFromJson(Map<String, dynamic> json) => DailyValues(
      cloudBaseAvg: (json['cloudBaseAvg'] as num?)?.toDouble(),
      cloudBaseMax: (json['cloudBaseMax'] as num?)?.toDouble(),
      cloudBaseMin: (json['cloudBaseMin'] as num?)?.toDouble(),
      cloudCeilingAvg: (json['cloudCeilingAvg'] as num?)?.toDouble(),
      cloudCeilingMax: (json['cloudCeilingMax'] as num?)?.toDouble(),
      cloudCeilingMin: (json['cloudCeilingMin'] as num?)?.toDouble(),
      cloudCoverAvg: (json['cloudCoverAvg'] as num?)?.toInt(),
      cloudCoverMax: (json['cloudCoverMax'] as num?)?.toInt(),
      cloudCoverMin: (json['cloudCoverMin'] as num?)?.toInt(),
      dewPointAvg: (json['dewPointAvg'] as num?)?.toDouble(),
      dewPointMax: (json['dewPointMax'] as num?)?.toDouble(),
      dewPointMin: (json['dewPointMin'] as num?)?.toDouble(),
      freezingRainIntensityAvg:
          (json['freezingRainIntensityAvg'] as num?)?.toInt(),
      freezingRainIntensityMax:
          (json['freezingRainIntensityMax'] as num?)?.toInt(),
      freezingRainIntensityMin:
          (json['freezingRainIntensityMin'] as num?)?.toInt(),
      hailProbabilityAvg: (json['hailProbabilityAvg'] as num?)?.toDouble(),
      hailProbabilityMax: (json['hailProbabilityMax'] as num?)?.toDouble(),
      hailProbabilityMin: (json['hailProbabilityMin'] as num?)?.toDouble(),
      hailSizeAvg: (json['hailSizeAvg'] as num?)?.toDouble(),
      hailSizeMax: (json['hailSizeMax'] as num?)?.toDouble(),
      hailSizeMin: (json['hailSizeMin'] as num?)?.toDouble(),
      humidityAvg: (json['humidityAvg'] as num?)?.toInt(),
      humidityMax: (json['humidityMax'] as num?)?.toInt(),
      humidityMin: (json['humidityMin'] as num?)?.toInt(),
      iceAccumulationAvg: (json['iceAccumulationAvg'] as num?)?.toInt(),
      iceAccumulationLweAvg: (json['iceAccumulationLweAvg'] as num?)?.toInt(),
      iceAccumulationLweMax: (json['iceAccumulationLweMax'] as num?)?.toInt(),
      iceAccumulationLweMin: (json['iceAccumulationLweMin'] as num?)?.toInt(),
      iceAccumulationLweSum: (json['iceAccumulationLweSum'] as num?)?.toInt(),
      iceAccumulationMax: (json['iceAccumulationMax'] as num?)?.toInt(),
      iceAccumulationMin: (json['iceAccumulationMin'] as num?)?.toInt(),
      iceAccumulationSum: (json['iceAccumulationSum'] as num?)?.toInt(),
      moonriseTime: json['moonriseTime'] == null
          ? null
          : DateTime.parse(json['moonriseTime'] as String),
      moonsetTime: json['moonsetTime'] == null
          ? null
          : DateTime.parse(json['moonsetTime'] as String),
      precipitationProbabilityAvg:
          (json['precipitationProbabilityAvg'] as num?)?.toInt(),
      precipitationProbabilityMax:
          (json['precipitationProbabilityMax'] as num?)?.toInt(),
      precipitationProbabilityMin:
          (json['precipitationProbabilityMin'] as num?)?.toInt(),
      pressureSeaLevelAvg: (json['pressureSeaLevelAvg'] as num?)?.toInt(),
      pressureSeaLevelMax: (json['pressureSeaLevelMax'] as num?)?.toInt(),
      pressureSeaLevelMin: (json['pressureSeaLevelMin'] as num?)?.toInt(),
      pressureSurfaceLevelAvg:
          (json['pressureSurfaceLevelAvg'] as num?)?.toInt(),
      pressureSurfaceLevelMax:
          (json['pressureSurfaceLevelMax'] as num?)?.toInt(),
      pressureSurfaceLevelMin:
          (json['pressureSurfaceLevelMin'] as num?)?.toInt(),
      rainAccumulationAvg: (json['rainAccumulationAvg'] as num?)?.toInt(),
      rainAccumulationLweAvg: (json['rainAccumulationLweAvg'] as num?)?.toInt(),
      rainAccumulationLweMax: (json['rainAccumulationLweMax'] as num?)?.toInt(),
      rainAccumulationLweMin: (json['rainAccumulationLweMin'] as num?)?.toInt(),
      rainAccumulationMax: (json['rainAccumulationMax'] as num?)?.toInt(),
      rainAccumulationMin: (json['rainAccumulationMin'] as num?)?.toInt(),
      rainAccumulationSum: (json['rainAccumulationSum'] as num?)?.toInt(),
      rainIntensityAvg: (json['rainIntensityAvg'] as num?)?.toInt(),
      rainIntensityMax: (json['rainIntensityMax'] as num?)?.toInt(),
      rainIntensityMin: (json['rainIntensityMin'] as num?)?.toInt(),
      sleetAccumulationAvg: (json['sleetAccumulationAvg'] as num?)?.toInt(),
      sleetAccumulationLweAvg:
          (json['sleetAccumulationLweAvg'] as num?)?.toInt(),
      sleetAccumulationLweMax:
          (json['sleetAccumulationLweMax'] as num?)?.toInt(),
      sleetAccumulationLweMin:
          (json['sleetAccumulationLweMin'] as num?)?.toInt(),
      sleetAccumulationLweSum:
          (json['sleetAccumulationLweSum'] as num?)?.toInt(),
      sleetAccumulationMax: (json['sleetAccumulationMax'] as num?)?.toInt(),
      sleetAccumulationMin: (json['sleetAccumulationMin'] as num?)?.toInt(),
      sleetIntensityAvg: (json['sleetIntensityAvg'] as num?)?.toInt(),
      sleetIntensityMax: (json['sleetIntensityMax'] as num?)?.toInt(),
      sleetIntensityMin: (json['sleetIntensityMin'] as num?)?.toInt(),
      snowAccumulationAvg: (json['snowAccumulationAvg'] as num?)?.toInt(),
      snowAccumulationLweAvg: (json['snowAccumulationLweAvg'] as num?)?.toInt(),
      snowAccumulationLweMax: (json['snowAccumulationLweMax'] as num?)?.toInt(),
      snowAccumulationLweMin: (json['snowAccumulationLweMin'] as num?)?.toInt(),
      snowAccumulationLweSum: (json['snowAccumulationLweSum'] as num?)?.toInt(),
      snowAccumulationMax: (json['snowAccumulationMax'] as num?)?.toInt(),
      snowAccumulationMin: (json['snowAccumulationMin'] as num?)?.toInt(),
      snowAccumulationSum: (json['snowAccumulationSum'] as num?)?.toInt(),
      snowIntensityAvg: (json['snowIntensityAvg'] as num?)?.toInt(),
      snowIntensityMax: (json['snowIntensityMax'] as num?)?.toInt(),
      snowIntensityMin: (json['snowIntensityMin'] as num?)?.toInt(),
      sunriseTime: json['sunriseTime'] == null
          ? null
          : DateTime.parse(json['sunriseTime'] as String),
      sunsetTime: json['sunsetTime'] == null
          ? null
          : DateTime.parse(json['sunsetTime'] as String),
      temperatureApparentAvg:
          (json['temperatureApparentAvg'] as num?)?.toDouble(),
      temperatureApparentMax:
          (json['temperatureApparentMax'] as num?)?.toDouble(),
      temperatureApparentMin:
          (json['temperatureApparentMin'] as num?)?.toDouble(),
      temperatureAvg: (json['temperatureAvg'] as num?)?.toDouble(),
      temperatureMax: (json['temperatureMax'] as num?)?.toDouble(),
      temperatureMin: (json['temperatureMin'] as num?)?.toDouble(),
      uvHealthConcernAvg: (json['uvHealthConcernAvg'] as num?)?.toInt(),
      uvHealthConcernMax: (json['uvHealthConcernMax'] as num?)?.toInt(),
      uvHealthConcernMin: (json['uvHealthConcernMin'] as num?)?.toInt(),
      uvIndexAvg: (json['uvIndexAvg'] as num?)?.toInt(),
      uvIndexMax: (json['uvIndexMax'] as num?)?.toInt(),
      uvIndexMin: (json['uvIndexMin'] as num?)?.toInt(),
      visibilityAvg: (json['visibilityAvg'] as num?)?.toInt(),
      visibilityMax: (json['visibilityMax'] as num?)?.toInt(),
      visibilityMin: (json['visibilityMin'] as num?)?.toInt(),
      weatherCodeMax: (json['weatherCodeMax'] as num?)?.toInt(),
      weatherCodeMin: (json['weatherCodeMin'] as num?)?.toInt(),
      windDirectionAvg: (json['windDirectionAvg'] as num?)?.toInt(),
      windGustAvg: (json['windGustAvg'] as num?)?.toDouble(),
      windGustMax: (json['windGustMax'] as num?)?.toDouble(),
      windGustMin: (json['windGustMin'] as num?)?.toDouble(),
      windSpeedAvg: (json['windSpeedAvg'] as num?)?.toDouble(),
      windSpeedMax: (json['windSpeedMax'] as num?)?.toDouble(),
      windSpeedMin: (json['windSpeedMin'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$DailyValuesToJson(DailyValues instance) =>
    <String, dynamic>{
      'cloudBaseAvg': instance.cloudBaseAvg,
      'cloudBaseMax': instance.cloudBaseMax,
      'cloudBaseMin': instance.cloudBaseMin,
      'cloudCeilingAvg': instance.cloudCeilingAvg,
      'cloudCeilingMax': instance.cloudCeilingMax,
      'cloudCeilingMin': instance.cloudCeilingMin,
      'cloudCoverAvg': instance.cloudCoverAvg,
      'cloudCoverMax': instance.cloudCoverMax,
      'cloudCoverMin': instance.cloudCoverMin,
      'dewPointAvg': instance.dewPointAvg,
      'dewPointMax': instance.dewPointMax,
      'dewPointMin': instance.dewPointMin,
      'freezingRainIntensityAvg': instance.freezingRainIntensityAvg,
      'freezingRainIntensityMax': instance.freezingRainIntensityMax,
      'freezingRainIntensityMin': instance.freezingRainIntensityMin,
      'hailProbabilityAvg': instance.hailProbabilityAvg,
      'hailProbabilityMax': instance.hailProbabilityMax,
      'hailProbabilityMin': instance.hailProbabilityMin,
      'hailSizeAvg': instance.hailSizeAvg,
      'hailSizeMax': instance.hailSizeMax,
      'hailSizeMin': instance.hailSizeMin,
      'humidityAvg': instance.humidityAvg,
      'humidityMax': instance.humidityMax,
      'humidityMin': instance.humidityMin,
      'iceAccumulationAvg': instance.iceAccumulationAvg,
      'iceAccumulationLweAvg': instance.iceAccumulationLweAvg,
      'iceAccumulationLweMax': instance.iceAccumulationLweMax,
      'iceAccumulationLweMin': instance.iceAccumulationLweMin,
      'iceAccumulationLweSum': instance.iceAccumulationLweSum,
      'iceAccumulationMax': instance.iceAccumulationMax,
      'iceAccumulationMin': instance.iceAccumulationMin,
      'iceAccumulationSum': instance.iceAccumulationSum,
      'moonriseTime': instance.moonriseTime?.toIso8601String(),
      'moonsetTime': instance.moonsetTime?.toIso8601String(),
      'precipitationProbabilityAvg': instance.precipitationProbabilityAvg,
      'precipitationProbabilityMax': instance.precipitationProbabilityMax,
      'precipitationProbabilityMin': instance.precipitationProbabilityMin,
      'pressureSeaLevelAvg': instance.pressureSeaLevelAvg,
      'pressureSeaLevelMax': instance.pressureSeaLevelMax,
      'pressureSeaLevelMin': instance.pressureSeaLevelMin,
      'pressureSurfaceLevelAvg': instance.pressureSurfaceLevelAvg,
      'pressureSurfaceLevelMax': instance.pressureSurfaceLevelMax,
      'pressureSurfaceLevelMin': instance.pressureSurfaceLevelMin,
      'rainAccumulationAvg': instance.rainAccumulationAvg,
      'rainAccumulationLweAvg': instance.rainAccumulationLweAvg,
      'rainAccumulationLweMax': instance.rainAccumulationLweMax,
      'rainAccumulationLweMin': instance.rainAccumulationLweMin,
      'rainAccumulationMax': instance.rainAccumulationMax,
      'rainAccumulationMin': instance.rainAccumulationMin,
      'rainAccumulationSum': instance.rainAccumulationSum,
      'rainIntensityAvg': instance.rainIntensityAvg,
      'rainIntensityMax': instance.rainIntensityMax,
      'rainIntensityMin': instance.rainIntensityMin,
      'sleetAccumulationAvg': instance.sleetAccumulationAvg,
      'sleetAccumulationLweAvg': instance.sleetAccumulationLweAvg,
      'sleetAccumulationLweMax': instance.sleetAccumulationLweMax,
      'sleetAccumulationLweMin': instance.sleetAccumulationLweMin,
      'sleetAccumulationLweSum': instance.sleetAccumulationLweSum,
      'sleetAccumulationMax': instance.sleetAccumulationMax,
      'sleetAccumulationMin': instance.sleetAccumulationMin,
      'sleetIntensityAvg': instance.sleetIntensityAvg,
      'sleetIntensityMax': instance.sleetIntensityMax,
      'sleetIntensityMin': instance.sleetIntensityMin,
      'snowAccumulationAvg': instance.snowAccumulationAvg,
      'snowAccumulationLweAvg': instance.snowAccumulationLweAvg,
      'snowAccumulationLweMax': instance.snowAccumulationLweMax,
      'snowAccumulationLweMin': instance.snowAccumulationLweMin,
      'snowAccumulationLweSum': instance.snowAccumulationLweSum,
      'snowAccumulationMax': instance.snowAccumulationMax,
      'snowAccumulationMin': instance.snowAccumulationMin,
      'snowAccumulationSum': instance.snowAccumulationSum,
      'snowIntensityAvg': instance.snowIntensityAvg,
      'snowIntensityMax': instance.snowIntensityMax,
      'snowIntensityMin': instance.snowIntensityMin,
      'sunriseTime': instance.sunriseTime?.toIso8601String(),
      'sunsetTime': instance.sunsetTime?.toIso8601String(),
      'temperatureApparentAvg': instance.temperatureApparentAvg,
      'temperatureApparentMax': instance.temperatureApparentMax,
      'temperatureApparentMin': instance.temperatureApparentMin,
      'temperatureAvg': instance.temperatureAvg,
      'temperatureMax': instance.temperatureMax,
      'temperatureMin': instance.temperatureMin,
      'uvHealthConcernAvg': instance.uvHealthConcernAvg,
      'uvHealthConcernMax': instance.uvHealthConcernMax,
      'uvHealthConcernMin': instance.uvHealthConcernMin,
      'uvIndexAvg': instance.uvIndexAvg,
      'uvIndexMax': instance.uvIndexMax,
      'uvIndexMin': instance.uvIndexMin,
      'visibilityAvg': instance.visibilityAvg,
      'visibilityMax': instance.visibilityMax,
      'visibilityMin': instance.visibilityMin,
      'weatherCodeMax': instance.weatherCodeMax,
      'weatherCodeMin': instance.weatherCodeMin,
      'windDirectionAvg': instance.windDirectionAvg,
      'windGustAvg': instance.windGustAvg,
      'windGustMax': instance.windGustMax,
      'windGustMin': instance.windGustMin,
      'windSpeedAvg': instance.windSpeedAvg,
      'windSpeedMax': instance.windSpeedMax,
      'windSpeedMin': instance.windSpeedMin,
    };
